version: '3'
services:
  httpd_service:
    image: 'httpd'
    ports:
      - '80:80'
    volumes:
      - '/mnt/wars:/usr/local/apache2/htdocs/'
        
  tomcat_service:
    image: 'tomcat:9'
    ports:
      - '8080-8085:8080'
    volumes:
      - '/mnt/tom/game-of-life/gameoflife-web/target:/usr/local/tomcat/webapps/'











